# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Thomas Pigeon
title: Third year PhD student
email: thomas.pigeon@inria.fr
website: https://thomaspigeon.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  thomaspigeon
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: thomas-pigeon-b10145155
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-7828-5128

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 I am a third year PhD student in theoretical chemistry under the supervision of Manuel Corral-Valero and [Pascal Raybaud](https://www.ifpenergiesnouvelles.fr/page/pascal-raybaud) at [IFPEN](https://www.ifpenergiesnouvelles.fr/) and [Gabriel Stoltz](https://cermics-lab.enpc.fr/gabriel-stoltz/) and [Tony Lelièvre](https://cermics.enpc.fr/~lelievre/) at [INRIA](https://team.inria.fr/matherials/). 
 
 My thesis work mixes a rare events sampling method (Adaptive Multi-level Splitting, AMS) and machine learning to identify reaction coordinates. The rare events at stake are molecular dynamics transition between identified meta-stable states (reactant/products). The target is to use machine learning method to define a one dimensional reaction coordinate which will serve to sample reactive trajectories and compute their occurrence probability. The transition mechanism can then be studied by analyzing these trajectories and from their occurrence probability, the reaction rate constant can be computed. 
 
 Relevant topics include:
 - Rare event sampling
 - Machine learned collective variables and reaction coordinates
 - Ab-initio molecular dynamics
 - Machine Learning force fields
 - Heterogeneous catalysis

content:
#  - title: Projects # Title for the section
#   layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Talks and Conferences # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - January 2023: [Mixed-Gen Season 3 – Session 3: Soft matter and machine learning](https://www.cecam.org/workshop-details/1185), *Exploring machine learned reaction coordinates in conjunction with rare events sampling methods in ab-initio molecular dynamics for catalytic reactions* ([Poster](./files/poster.pdf))
      - January 2023: [LIA annual meeting](https://www.lia-uiuc.cnrs.fr/), *Rare event sampling methods and machine learning to study catalytic reaction mechanisms* ([slides](./files/PresentationWorkshop_Hauteluce.pdf))
      - October 2022: [Machine Learning Meets Statistical Mechanics: Success and Future Challenges in Biosimulations](https://www.cecam.org/workshop-details/1153), *Exploring machine learned reaction coordinates in conjunction with rare events sampling methods in ab-initio molecular dynamics for catalytic reactions* ([Poster](./files/poster.pdf))
      - June 2022: [Chasing CVs using Machine Learning: from methods development to biophysical applications](https://www.cecam.org/workshop-details/1134), *Exploring machine learned reaction coordinates in conjunction with rare events sampling methods in ab-initio molecular dynamics for catalytic reactions* ([Poster](./files/poster.pdf))
      - June 2022: [International Conference on Theoretical Aspects of Catalysis](https://ictac2022.univ-lyon1.fr/en/pages/ictac-2022-home), *Exploring machine learned reaction coordinates in conjunction with rare events sampling methods in ab-initio molecular dynamics for catalytic reactions* ([Poster](./files/poster.pdf))
      - Mai 2022: Journée plénière GDR IAMAT, *Exploring machine learned reaction coordinates in conjunction with rare events sampling methods in ab-initio molecular dynamics for catalytic reactions* ([Poster](./files/poster.pdf))

  - title: Publications
    layout: text 
    content: |
      - Thomas Pigeon, Céline Chizallet, Pascal Raybaud. Revisiting γ-Alumina Surface Models through the Topotactic Transformation of Boehmite Surfaces. Journal of Catalysis, (2022), 405, (doi:[https://doi.org/10.1016/j.jcat.2021.11.011](https://doi.org/10.1016/j.jcat.2021.11.011))
      - F. Guégan, T. Pigeon, F. De Proft, V. Tognetti, L. Joubert, H. Chermette,P.W. Ayers, D. Luneau, C. Morell, Understanding Chemical Selectivity through Well Selected Excited States, Journal of Physical Chemistry A, (2020), 124 (doi:[10.1021/acs.jpca.9b09978](10.1021/acs.jpca.9b09978))
      - Ana T.F. Batista, Dorothea Wisser, Thomas Pigeon, David Gajan, Fabrice Diehl, Mickael Rivallan, Leonor Catita, Anne-Sophie Gay, Anne Lesage, Céline Chizallet, Pascal Raybaud, Beyond γ-Al2O3 crystallite surfaces: The hidden features of edges revealed by solid-state 1H NMR and DFT calculations, Journal of Catalysis,  (2019), 378, (doi:[https://doi.org/10.1016/j.jcat.2019.08.009](https://doi.org/10.1016/j.jcat.2019.08.009))

  - title: Preprint
    layout: text
    content: |
      - Thomas Pigeon, Gabriel Stoltz, Manuel Corral-Valero, Ani Anciaux-Sedrakian, Maxime Moreaud, Tony Lelièvre, Pascal Raybaud, Computing Surface Reaction Rates by Adaptive Multilevel Splitting Combined with Machine Learning and Ab Initio Molecular Dynamics, ([arXiv:2303.05993v1](https://arxiv.org/abs/2303.05993v1))

# Footer
#footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
