# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Thomas Pigeon
title: Research engineer at IFP Energies Nouvelles
email: thomas.pigeon@ifpen.fr
website: https://thomaspigeon.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  thomaspigeon
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: thomas-pigeon-b10145155
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-7828-5128

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/photo_perso_1.jpg
about_content: | # this will include new lines to allow paragraphs
 I am a research engineer at IFP Energies nouvelles since december 2023. I did a PhD in theoretical chemistry (2023) under the supervision of Manuel Corral-Valero and [Pascal Raybaud](https://www.ifpenergiesnouvelles.fr/page/pascal-raybaud) at [IFPEN](https://www.ifpenergiesnouvelles.fr/) and [Gabriel Stoltz](https://cermics-lab.enpc.fr/gabriel-stoltz/) and [Tony Lelièvre](https://cermics.enpc.fr/~lelievre/) at [INRIA](https://team.inria.fr/matherials/). 
 
 My thesis work mixes a rare events sampling method (Adaptive Multi-level Splitting, AMS) and machine learning to identify reaction coordinates. The rare events at stake are molecular dynamics transition between identified meta-stable states (reactant/products). The target is to use machine learning method to define a one dimensional reaction coordinate which will serve to sample reactive trajectories and compute their occurrence probability. The transition mechanism can then be studied by analyzing these trajectories and from their occurrence probability, the reaction rate constant can be computed. 
 
 Relevant topics include:
 - Rare event sampling
 - Machine learned collective variables and reaction coordinates
 - Ab-initio molecular dynamics
 - Machine Learning force fields
 - Heterogeneous catalysis

 Here is my resume ([pdf](./files/resume.pdf)).
 
content:
#  - title: Projects # Title for the section
#   layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Talks and Conferences # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - July 2024: [ICC 2024](https://www.icc-lyon2024.fr/), *Computing catalytic reaction times and paths with machine learning and rare events sampling methods* ([Slides](./files/Thomas_Pigeon_ICC2024.pdf))
      - April 2024: [Learning collective variables and coarse grained models](https://www.imsi.institute/activities/data-driven-materials-informatics/learning-collective-variables-and-coarse-grained-models/), *Estimating committor function using rare event sampling* ([Poster](./files/poster_committor.pdf))
      - April 2024: [Machine Learning Force Fields](https://www.imsi.institute/activities/data-driven-materials-informatics/machine-learning-force-fields/), *Computing surface reaction rate using machine learning inter-atomic potential* ([Slides](./files/MLFF_Pigeon_Thomas.pdf))
      - August 2023: [Europacat 2023](https://www.europacat2023.cz/), *Computing reaction times and paths with machine learning and rare event sampling methods* ([Slides](./files/Thomas_Pigeon_europacat.pdf))
      - August 2023: [ACS fall 2023](https://www.acs.org/meetings/acs-meetings/fall-2023.html), *Computing reaction times and paths with machine learning and rare event sampling methods* ([Slides](./files/Thomas_Pigeon_ACS_fall.pdf))
      - June 2023: [14 international conference on Monte Carlo Methods and Applications (MCM2023)](https://mcm2023.sciencesconf.org/), *Adaptive multilevel splitting to machine learn committor function* ([Slides](./files/MCM_2023.pdf)) 
      - January 2023: [Mixed-Gen Season 3 – Session 3: Soft matter and machine learning](https://www.cecam.org/workshop-details/1185), *Exploring machine learned reaction coordinates in conjunction with rare events sampling methods in ab-initio molecular dynamics for catalytic reactions* ([Poster](./files/poster.pdf))
      - January 2023: [LIA annual meeting](https://www.lia-uiuc.cnrs.fr/), *Rare event sampling methods and machine learning to study catalytic reaction mechanisms* ([slides](./files/PresentationWorkshop_Hauteluce.pdf))
      - January 2023: IFP Energies nouvelles catalysis, biocatalysis and separation PhD student workshop, *Rare event sampling methods and machine learning to study catalytic reaction mechanisms* ([slides](./files/PresentationWorkshop_Hauteluce.pdf))
      - October 2022: [Machine Learning Meets Statistical Mechanics: Success and Future Challenges in Biosimulations](https://www.cecam.org/workshop-details/1153), *Exploring machine learned reaction coordinates in conjunction with rare events sampling methods in ab-initio molecular dynamics for catalytic reactions* ([Poster](./files/poster.pdf))
      - June 2022: [Chasing CVs using Machine Learning: from methods development to biophysical applications](https://www.cecam.org/workshop-details/1134), *Exploring machine learned reaction coordinates in conjunction with rare events sampling methods in ab-initio molecular dynamics for catalytic reactions* ([Poster](./files/poster.pdf))
      - June 2022: [International Conference on Theoretical Aspects of Catalysis](https://ictac2022.univ-lyon1.fr/en/pages/ictac-2022-home), *Exploring machine learned reaction coordinates in conjunction with rare events sampling methods in ab-initio molecular dynamics for catalytic reactions* ([Poster](./files/poster.pdf))
      - Mai 2022: Journée plénière GDR IAMAT, *Exploring machine learned reaction coordinates in conjunction with rare events sampling methods in ab-initio molecular dynamics for catalytic reactions* ([Poster](./files/poster.pdf))
      - February 2021: ROAD4CAT chair annual meeting, *From boehmite to γ-alumina edges : revisiting the nature of sites and deciphering 1H NMR experiments* ([slides](./files/ROAD4CAT.pdf))

  - title: Publications
    layout: text 
    content: |
      - D. Gioffrè, P. Florian, T. Pigeon, P. Raybaud, C. Chizallet, C. Copéret, Classification and Identification of Facet- and Edge-Specific γ-Al2O3 Surface Sites from 1H/27Al NMR Cross-Signatures and DFT Modeling, J. Am. Chem. Soc. (2025), 147, 8, 6934-6941 (doi:[https://doi.org/10.1021/jacs.4c17358](https://doi.org/10.1021/jacs.4c17358))
      - T. Lelièvre, T. Pigeon, G. Stoltz, W. Zhang, Analyzing multimodal probability measures with autoencoders, J. Phys. Chem. B, (2024), 128, 11, 2607–2631 (doi:[https://doi.org/10.1021/acs.jpcb.3c07075](https://doi.org/10.1021/acs.jpcb.3c07075))      
      - T. Pigeon, G. Stoltz, M. Corral-Valero, A. Anciaux-Sedrakian, M. Moreaud, T. Lelièvre, P. Raybaud, Computing Surface Reaction Rates by Adaptive Multilevel Splitting Combined with Machine Learning and Ab Initio Molecular Dynamics, J. Chem. Theory Comput. (2023)  (doi:[https://doi.org/10.1021/acs.jctc.3c00280](https://doi.org/10.1021/acs.jctc.3c00280))
      - A.T.F. Batista, T. Pigeon, J. Meyet, D. Wisser, M. Rivallan, D. Gajan, L. Catita, F. Diehl, A-S. Gay, C. Chizallet, A. Lesage, P. Raybaud, Structure, location, and spatial proximities of hydroxyls on γ-alumina crystallites by high-resolution solid-State NMR and DFT modeling: why edges hold the key, ACS Catal. (2023), 6536–6548 (doi:[https://doi.org/10.1021/acscatal.3c00495](https://doi.org/10.1021/acscatal.3c00495))
      - T. Pigeon, C. Chizallet, P. Raybaud. Revisiting γ-Alumina Surface Models through the Topotactic Transformation of Boehmite Surfaces. Journal of Catalysis, (2022), 405, (doi:[https://doi.org/10.1016/j.jcat.2021.11.011](https://doi.org/10.1016/j.jcat.2021.11.011))
      - F. Guégan, T. Pigeon, F. De Proft, V. Tognetti, L. Joubert, H. Chermette,P.W. Ayers, D. Luneau, C. Morell, Understanding Chemical Selectivity through Well Selected Excited States, Journal of Physical Chemistry A, (2020), 124 (doi:[10.1021/acs.jpca.9b09978](10.1021/acs.jpca.9b09978))
      - A.T.F. Batista, D. Wisser, T. Pigeon, D. Gajan, F. Diehl, M. Rivallan, L. Catita, A.S. Gay, A. Lesage, C. Chizallet, P. Raybaud, Beyond γ-Al2O3 crystallite surfaces: The hidden features of edges revealed by solid-state 1H NMR and DFT calculations, Journal of Catalysis,  (2019), 378, (doi:[https://doi.org/10.1016/j.jcat.2019.08.009](https://doi.org/10.1016/j.jcat.2019.08.009))

#  - title: Preprint
#   layout: text
#    content: |
#      - T. Lelièvre, T. Pigeon, G. Stoltz, W. Zhang, Analyzing multimodal probability measures with autoencoders, ([arXiv:2310.03492](https://arxiv.org/abs/2310.03492))

  - title: Distinctions
    layout: text
    content: |
      - Poster prize, [International Conference on Theoretical Aspects of Catalysis](https://ictac2022.univ-lyon1.fr/en/pages/ictac-2022-home), (2022)
      - Presentation price, IFP Energies nouvelles catalysis, biocatalysis and separation divsion PhD workshop, (2022)    
# Footer
#footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
